exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

markdown: redcarpet

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: Trillium Newfoundlands
author:
  name:
  email: kligallery@msn.com
  github: kligallery
  twitter: kligallery

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
# baseurl: trilliumnewfs.com

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics:
  google:
    tracking_id: 'UA-50797813-1'
    verification: 'V78NvqcWfDcIQguMM1QQb5rwPXKArTcRbcReljIKzx4'
